### ISSUE TITLE
Video playback is not smooth

### ISSUE THREAD

**Issue by karthik-m1** [NUStreaming/acm-mmsys-2020-grand-challenge#3]
Setup was done based on instructions , but video playback is not smooth.

and on running node run.js
Below error are shown.
for await (const profile of pattern) {
      ^^^^^

SyntaxError: Unexpected reserved word
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
    at startup (bootstrap_node.js:204:16)
    at bootstrap_node.js:625:3

**Comment by akouSDN** [comment]
please refer to my previous post

**Comment by karthik-m1** [comment]
> please refer to my previous post

can you please share previous post link

**Comment by akouSDN** [comment]
> > please refer to my previous post
> 
> can you please share previous post link
[Here](https://github.com/NUStreaming/LoL/issues/4)
